name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: install
      run: npm i

    - name: test
      run: npm run test

